<?php

namespace app\modules\api\v1\models;


use app\models\Upload;
use yii\helpers\Url;
use yii\web\Linkable;
class ApiModel  extends Upload implements Linkable
{

    /**
     * @return array
     */
    public function rules()
    {
        return [
            [['type'], 'required'],
            [['type', 'user_id'], 'integer'],
            [['name', 'size', 'date', 'unique_name'], 'string'],
            [['file'], 'file', 'extensions' => 'docx, doc, pdf, xls, xlsx, odt, ods, odp, rtf, txt', 'maxSize' => '20000000']
        ];
    }

    
    /**
     * @return array|false|int[]|string[]
     */
    public function fields()
    {
        $fields = parent::fields();

        unset($fields['user_id']);

        return $fields;
    }

    /**
     * @return array|false|int[]|string[]
     */
    public function extraFields()
    {
        return parent::extraFields(); // TODO: Change the autogenerated stub
    }

    /**
     * @return array
     */
    public function getLinks(): array
    {
        return [
            'viewLink' => Url::to(['/upload/view', 'id' => $this->id], true),
        ];
    }
}