<?php

namespace app\modules\api\v1\models;

use dektrium\user\models\User;


class AuthModel extends User
{
    /**
     * @return array|false|int[]|string[]
     */
    public function fields()
    {
        return parent::fields();
    }

    /**
     * @return array|false|int[]|string[]
     */
    public function extraFields()
    {
        return parent::extraFields(); // TODO: Change the autogenerated stub
    }

}