<?php

namespace app\modules\api\v1\models;

use dektrium\user\models\User;


class UserModel extends User
{
    /**
     * @return array|false|int[]|string[]
     */
    public function fields()
    {
        $fields = parent::fields();

        unset($fields['password_hash']);
        unset($fields['auth_key']);

        return $fields;
    }

    /**
     * @return array|false|int[]|string[]
     */
    public function extraFields()
    {
        return parent::extraFields(); // TODO: Change the autogenerated stub
    }

}